//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Character')
export class CharacterEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  author: string;

  @Column('text', { nullable: true })
  characterName: string;

  @Column('integer', { nullable: true })
  expressions: number;
}
