//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Expressions')
export class ExpressionsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  expressionText: string;

  @Column('text', { nullable: true })
  emotion: string;

  @Column('text', { nullable: true })
  triggerQuestionKeywords: string;
}
