//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('UserInteractions')
export class UserInteractionsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  userID: number;

  @Column('text', { nullable: true })
  question: string;

  @Column('integer', { nullable: true })
  response: number;

  @Column('date', { nullable: true })
  timestamp: Date;

  @Column('integer', { nullable: true })
  characterUsed: number;
}
