//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('User')
export class UserEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  username: string;

  @Column('text', { nullable: true })
  email: string;

  @Column('text', { nullable: true })
  passwordHash: string;

  @Column('date', { nullable: true })
  signUpDate: Date;

  @Column('date', { nullable: true })
  lastLogin: Date;
}
