//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const UserInteractionsTitle = () => {
  const record = useRecordContext();
  return <span>UserInteractions {record ? `"${record.question}"` : ''}</span>;
};

export const UserInteractionsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <ReferenceField source="userID" reference="User" />
      <TextField source="question" />
      <ReferenceField source="response" reference="Expressions" />
      <DateField source="timestamp" />
      <ReferenceField source="characterUsed" reference="Character" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const UserInteractionsEdit = () => (
  <Edit title={<UserInteractionsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="userID" reference="User" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="question" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="response" reference="Expressions" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="timestamp" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="characterUsed" reference="Character" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const UserInteractionsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="userID" reference="User" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="question" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="response" reference="Expressions" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="timestamp" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="characterUsed" reference="Character" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  <ReferenceInput source="userID" label="userID" reference="User" alwaysOn />,
  ,
  <ReferenceInput
    source="response"
    label="response"
    reference="Expressions"
    alwaysOn
  />,
  ,
  <ReferenceInput
    source="characterUsed"
    label="characterUsed"
    reference="Character"
    alwaysOn
  />,
];
